# _config.yml
# サイトの基本設定
locale: "ja-JP" # 日本語設定
title: "SRE データ分析教材" # サイトのタイトル
title_separator: "|"
name: "SRE Data Analytics Team" # サイトの名前
description: "SRE Data Analytics Teamのデータ分析教材です。" # サイトの説明
url: "https://lcp-business-sre.github.io/" # サイトのベースURL (GitHub Pagesのドメイン)
baseurl: "/data-analytics-knowledge-base" # GitHub Pagesのサブパス (例: /my-course)。ユーザーページなら ""
repository: "https://lcp-business-sre.github.io/data-analytics-knowledge-base" # GitHubリポジトリ名 (GitHub Pagesにプッシュする場合)
words_per_minute: 200 # 読書時間の計算用 (オプション)

# テーマ設定
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # Minimal MistakesテーマをGemで読み込む

# minimal_mistakes_skin: "default" # Minimal Mistakesのスキン設定 (オプション)
minimal_mistakes_skin: "aqua"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-remote-theme
  - jekyll-include-cache

logo: "/assets/images/bio-photo.png" # サイトロゴのパス (存在すれば設定) 

# 【重要】Minimal Mistakesのスキン設定をコメントアウトまたは削除
# これにより、_sass/custom/_colors.scss で完全に色を制御します。
# minimal_mistakes_skin: "default"

enable_emoji: true # 絵文字を有効にする
enable_copy_button: true # コードブロックにコピー機能を追加

# Markdownレンダリング設定
kramdown:
  auto_ids: true
  auto_id_prefix: "markdown-"
  syntax_highlighter: rouge # コードハイライトエンジン
  syntax_highlighter_opts:
    block:
      line_numbers: true # コードブロックに行番号を表示

search_enabled: true # 検索機能を有効にする
search: true

# 除外ファイル (ビルド時に処理しないファイル/ディレクトリ)
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # docs/ はMinimal Mistakesのドキュメントなので、削除したい場合はこの行を有効にする
  # - docs/ 
  # CNAME はGitHub Pagesカスタムドメイン用なので、不要なら削除してこの行を有効にする
  # - CNAME 

# 各ページのデフォルト設定
defaults:
  # _pages ディレクトリ内のすべてのMarkdownファイルに適用
  - scope:
      path: "_pages" # このパス以下のファイルに適用
    values:
      layout: "single" # Minimal Mistakesの標準的なページレイアウト
      # サイドバーナビゲーションを有効にする設定
      sidebar:
        nav: "docs" # _data/navigation.yml で定義したサイドバーナビゲーションのID
      # 目次を自動生成する場合 (オプションだが教材に推奨)
      toc: true
      # toc_label: "このページの目次" # 目次のタイトル
      # toc_icon: "fa-solid fa-list-ul" # 目次のアイコン (Font Awesome)
      toc_sticky: true # 目次をスクロールしてもサイドバーに固定表示

# 著者情報 (オプション: 必要に応じて更新)
author:
  name: "著者名"
  # avatar: "/assets/images/bio-photo.jpg" # アバター画像のパス (存在すれば設定)
  bio: "SRE Data Analytics Team" # 簡単な自己紹介
  location: "Tokyo, Japan" # 所在地
  uri: "https://sites.google.com/mb.lecip.co.jp/business-dx/dx-sol" # あなたのウェブサイト
  email: "your@email.com"
  github: "lcp-business-SRE" # あなたのGitHubユーザー名