# _config.yml
# サイトの基本設定
locale: "ja-JP" # 日本語設定
title: "Minimal Mistakes教材サイト"
title_separator: "|"
name: "あなたの名前"
description: "Minimal Mistakesテーマを使った教材サイトのサンプルです。"
url: "https://lcp-business-sre.github.io/" # サイトのベースURL (GitHub Pagesのドメイン)
baseurl: "/data-analytics-knowledge-base" # GitHub Pagesのサブパス (例: /my-course)。ユーザーページなら ""
repository: "あなたのGitHubユーザー名/my-course" # GitHubリポジトリ名 (GitHub Pagesにプッシュする場合)
words_per_minute: 200 # 読書時間の計算用 (オプション)

# テーマ設定
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # Minimal MistakesテーマをGemで読み込む
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-remote-theme
  - jekyll-include-cache

# 【重要】Minimal Mistakesのスキン設定をコメントアウトまたは削除
# これにより、_sass/custom/_colors.scss で完全に色を制御します。
# minimal_mistakes_skin: "default"

# Markdownレンダリング設定
kramdown:
  auto_ids: true
  auto_id_prefix: "markdown-"
  syntax_highlighter: rouge # コードハイライトエンジン
  syntax_highlighter_opts:
    block:
      line_numbers: true # コードブロックに行番号を表示

# 除外ファイル (ビルド時に処理しないファイル/ディレクトリ)
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # docs/ はMinimal Mistakesのドキュメントなので、削除したい場合はこの行を有効にする
  # - docs/ 
  # CNAME はGitHub Pagesカスタムドメイン用なので、不要なら削除してこの行を有効にする
  # - CNAME 

# 各ページのデフォルト設定
defaults:
  # _pages ディレクトリ内のすべてのMarkdownファイルに適用
  - scope:
      path: "_pages" # このパス以下のファイルに適用
    values:
      layout: "single" # Minimal Mistakesの標準的なページレイアウト
      # サイドバーナビゲーションを有効にする設定
      sidebar:
        nav: "docs" # _data/navigation.yml で定義したサイドバーナビゲーションのID
      # 目次を自動生成する場合 (オプションだが教材に推奨)
      # toc: true
      # toc_label: "このページの目次" # 目次のタイトル
      # toc_icon: "fa-solid fa-list-ul" # 目次のアイコン (Font Awesome)
      # toc_sticky: true # 目次をスクロールしてもサイドバーに固定表示

# 著者情報 (オプション: 必要に応じて更新)
author:
  name: "著者名"
  # avatar: "/assets/images/bio-photo.jpg" # アバター画像のパス (存在すれば設定)
  bio: "Jekyll学習中の著者です。"
  uri: "https://your-website.com" # あなたのウェブサイト
  email: "your@email.com"
  github: "your_github_username" # あなたのGitHubユーザー名