baseURL = 'https://lcp-business-sre.github.io/data-analytics-knowledge-base/'
languageCode = "ja-jp"
title = "データサイエンス育成教材"
theme = "hugo-book"

[params]
  # Bookテーマの各種設定（任意）
  # https://alex-shpak.github.io/hugo-book/docs/configuration/
  # 例:
  #  BookMenuBundle = "/menu" # メニューの表示を制御するバンドル
  #  BookSearch = true # 検索機能の有効化
  #  BookCollapseSection = true # セクションの折りたたみ
  #  BookFlatMenu = true # フラットなメニュー表示

[menu]
  [[menu.main]]
    pageRef = "/docs/introduction" # 各章へのリンクをここに記述
    name = "はじめに"
    weight = 1
  [[menu.main]]
    pageRef = "/docs/basic-stats"
    name = "統計の基礎"
    weight = 2
  # 以下、必要に応じて追加