import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {

  dataAnalysisSidebar: [
    {
      type: 'category',
      label: 'イントロダクション',
      link: {
        type: 'doc',
        id: 'data-analysis/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'data-analysis/index', // docs/data-analytics/fundamentals から自動生成
        },
      ],
    },
    {
      type: 'category',
      label: 'データ分析の基礎',
      link: {
        type: 'doc',
        id: 'data-analysis/fundamentals/index', // 基礎のトップページにリンク
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'data-analysis/fundamentals', // docs/data-analytics/fundamentals から自動生成
        },
      ],
    },
    {
      type: 'category',
      label: 'データ分析の応用',
      link: {
        type: 'doc',
        id: 'data-analysis/applications/index', // 応用のトップページにリンク
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'data-analysis/applications', // docs/data-analytics/applications から自動生成
        },
      ],
    },
  ],

  // データ基盤のサイドバー
  dataPlatformSidebar: [
    {
      type: 'category',
      label: 'イントロダクション',
      link: {
        type: 'doc',
        id: 'data-platform/index', // 基礎のトップページにリンク
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'data-platform/index', // docs/data-platform/fundamentals から自動生成
        },
      ],
    },
    {
      type: 'category',
      label: 'データ基盤の基礎',
      link: {
        type: 'doc',
        id: 'data-platform/fundamentals/index', // 基礎のトップページにリンク
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'data-platform/fundamentals', // docs/data-platform/fundamentals から自動生成
        },
      ],
    },
    {
      type: 'category',
      label: 'データ基盤の応用',
      link: {
        type: 'doc',
        id: 'data-platform/applications/index', // 応用のトップページにリンク
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'data-platform/applications', // docs/data-platform/applications から自動生成
        },
      ],
    },
  ],
  };

export default sidebars;
