name: Deploy to GitHub Pages

defaults:
  run:
    shell: bash
    working-directory: ./data-analytics-guides # このディレクトリ内でrunコマンドが実行される

on:
  push:
    branches:
      # - main
      - master # masterブランチへのpushでトリガー

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          # ここが重要: ロックファイルのパスを明示的に指定
          cache-dependency-path: ./data-analytics-guides/package-lock.json # または yarn.lock

      - name: Install dependencies
        run: npm ci # package-lock.jsonに基づいて依存関係をインストール
      - name: Build website
        run: npm run build # Docusaurus のビルドコマンド

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Docusaurus のビルド出力ディレクトリへのパスを修正
          # working-directoryが適用されるrunコマンドとは異なり、
          # このアクションはリポジトリのルートを基準にパスを解釈します。
          path: ./data-analytics-guides/build 

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
